version: "3.8"
services:
  postgres:
    build: ./
    image: pomodoro-db:24.06.20
    container_name: pomodoro-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
volumes:
  postgres-data:
